src/Connection.php
fix this case:
```
$connection->query('INSERT INTO book (name, ISBN, author, created) VALUES (?, ?, ?, ?)',
$name, $isbn, $author, 0);
```
which give:
`Fatal error: Uncaught LogicException: Params not enouth to build sql in src/Query.php:120`
=> last query param can be lost

.gitignore, tests/BaseTestCase.php, tests/ConnectionTest.php, tests/ResultQueryTest.php, tests/dataset.yaml
For now, in all test cases, MySQL connection parameters are hardcoded so I propose to use parameters from phpunit.xml.
Also, I added 'create table' query into 'getConnection' method of 'BaseTestCase' so now we may just run phpunit without any manipulation of the database.
=> Allow to change default MySQL connection parameters in test cases

src/Connection.php
Allow the user of the API to parse a custom Connector, so he can use it's own DNS Resolver. This is especially valid when working in a docker based environment, as docker uses it's own DNS server, so with the current solution, the names of the other docker container wont resolve
=> Allow for custom Connector / DNS Resolver

README.md, src/Connection.php
This simple PR adds documentation for the `Connection` class and how an explicit instance of `ConnectorInterface` can be passed to it. This also removes the hard-coded default DNS server and makes sure this will be applied automatically once https://github.com/reactphp/socket/issues/90 is in (which I'm currently working on).
=> Documentation for Connection (and custom Connector)

README.md, composer.json
This is now a community project managed by @friends-of-reactphp. The original implementation was created by @bixuehujin starting in 2013 and has been migrated to @friends-of-reactphp to help with maintenance and upcoming feature development.
Thank you @bixuehujin for the initial work and for transferring ownership!
I would also like to thank @kakserpom for confirming that the protocol implementation is used in accordance with [phpdaemon](https://github.com/kakserpom/phpdaemon)'s license.
Supersedes / closes #13
Supersedes / closes #31
=> Migrate to @friends-of-reactphp, thank you @bixuehujin!

README.md, examples/init.php, examples/query-with-callback.php, src/Connection.php, src/ConnectionInterface.php, tests/ConnectionTest.php
This PR ensures consistent connect() behavior for all connection states. This implies that calling `connect()` in an invalid state (i.e. calling it more than once) will not throw an exception and is now in line with the other methods.
The code change is rather trivial, most of this changeset is about tests to ensure consistent behavior for the current API and documentation for this.
Resolves / closes #6
=> Consistent connect() behavior for all connection states

composer.json
Builds on top of #30 as this no longer has an explicit dependency on react/dns.
=> Forward compatibility with upcoming ReactPHP components

src/Connection.php, src/Query.php, tests/QueryTest.php, tests/ResultQueryTest.php
This PR ensures that the `Query` class will only try to replace question marks in the given SQL string if bind params have actually been passed explicitly. If no bind params have been passed, it will no longer try to replace any params and thus no longer complain about missing params.
Resolves / closes #15 
Builds on top of #39
=> Fix parameter binding if query contains question marks

src/Protocal/Parser.php, tests/BaseTestCase.php, tests/ResultQueryTest.php
This PR first adds a number of test cases to very what kind of values can be processed and subsequently fixes reading empty rows containing only empty string columns.
Previously, the protocol parser would fail for all result sets that contain a single row that consists of only empty string values, for example:
```
SELECT ""
SELECT 1 UNION SELECT ""
SELECT "", ""
```
Resolves / closes #28
=> Fix reading empty rows containing only empty string columns 

src/ConnectionInterface.php, src/Protocal/Parser.php, tests/ResultQueryTest.php
This PR disables the (broken) support for multiple statements for security and API reasons. Sending multiple statements as a single query could allow for possible SQL injection attacks if the input is not properly escaped. Also, the current API has no (sane) way of exposing multiple results (such as multiple independent result sets).
I do not consider this to be a BC break because the current API has no sane way of exposing multiple results in the first place and the test suite does not contain any mention of this. This PR adds a test to ensure queries with multiple statements are now properly rejected.
We will likely look into this again for a future version, once the current API issues have been worked out. Possible future implementation ideas: Exposing numbered sets à la …
=> Do not support multiple statements for security and API reasons

src/Command.php, src/Connection.php, src/Protocal/Parser.php, tests/ConnectionTest.php, tests/Protocal/ParserTest.php
This PR ensures that all outstanding commands will be rejected if the connection is closed.
As a first step, this PR performs a minor refactoring to avoid accessing an internal queue that only ever has a maximum of one single command anyway. This is not a BC break because its outside behavior is preserved (tests are not affected). Additionally, it ensures that the current command and any queued ones will be properly rejected with an `error` event the connection is closed.
Resolves / closes #44
=> Reject pending commands if connection is closed

src/Command.php, src/Commands/QueryCommand.php, src/Connection.php, src/Io/Binary.php, src/Io/Constants.php, src/Io/EventEmitter.php, src/Io/Executor.php, src/Io/Parser.php, src/Io/Query.php, tests/Io/ParserTest.php, tests/Io/QueryTest.php, tests/ResultQueryTest.php
As a first step for the upcoming v0.4.0 release, this simple PR marks all internal classes as `@internal` and moves them to a new `React\MySQL\Io` namespace.
This is technically a BC break because consumers could potentially rely on these classes, but there's no reasons to believe this is actually done in the wild and as such should not affect "normal" usage as described in our documentation. Marking these classes as `@internal` allows us to perform some (significant) changes to them without causing additional BC breaks, as consumers are now explicitly discouraged from using them in their code.
=> Mark all protocol logic classes as internal and move to new Io namespace

README.md, examples/02-query-stream.php, src/Connection.php, src/ConnectionInterface.php, src/Io/Parser.php, tests/BaseTestCase.php, tests/ResultQueryTest.php
This PR adds a new `queryStream()` method which allows processing larger result sets with hundreds or thousands of records, so that one is no longer limited by memory in how many records can be processed. Its API can be used like this:
```php
$stream = $connection->queryStream('SELECT * FROM users');
$stream->on('data', function ($row) {
var_dump($row);
});
$stream->on('end', function () {
echo 'DONE' . PHP_EOL;
});
```
Being a new addition to the `ConnectionInterface`, this PR is technically a BC break. This also includes a small patch to ensure that results are no longer buffered internally in the `Parser` and removes its undocumented `results` event. Empirical evidence suggests this should not affect most consumers.
Builds on top of #54
Resolves / closes #50
=> Add queryStream() method to stream result set rows and remove undocumented "results" event

src/Io/Buffer.php, src/Io/Constants.php, src/Io/Parser.php, tests/Io/BufferTest.php
Instead of simply discarding all unknown outstanding data at the end of each packet, we now properly parse the whole packet until its end. If anything would be remaining at the end, this would cause a parsing error for the following packets.
This fixes a subtle bug introduced with https://github.com/friends-of-reactphp/mysql/pull/54/files#diff-2031b03ede17eedd651eae219aa02d8fR88 which caused some outstanding data in long response packets to interfere with the following incoming packets.
This only affects the current master branch and only affects rather long response messages with at least ~16000 entries which is why this wasn't caught by the test suite previously.
Resolves / closes #58 
Builds on top of #54
=> Fix reading all incoming response packets until end

src/Connection.php, src/ConnectionInterface.php
Both methods are not really needed. While the `listFields()` method is only a dummy with no function at all, the `selectDb()` method can simply be replaced by a query like this:
```php
// old
$connection->selectDb('test');
// new (already supported before)
$connection->query('USE test');
```
=> Remove unneeded `listFields()` dummy and `selectDb()` method

README.md, composer.json, examples/01-query.php, examples/11-interactive.php, src/Connection.php, src/ConnectionInterface.php, tests/ConnectionTest.php, tests/NoResultQueryTest.php, tests/ResultQueryTest.php
This PR updates the `query()` method to use promises instead of accepting an optional callback function. The updated `query()` method also accepts an array of query parameters for consistency with the `queryStream()` method (#57):
```php
// old
$connection->query('CREATE TABLE test');
$connection->query('DELETE FROM user WHERE id < ?', $id);
$connection->query('SELECT * FROM user', function (QueryCommand $command) {
if ($command->hasError()) {
echo 'Error: ' . $command->getError()->getMessage() . PHP_EOL;
} elseif (isset($command->resultRows)) {
var_dump($command->resultRows);
}
});
// new
$connection->query('CREATE TABLE test');
$connection->query('DELETE FROM user WHERE id < ?', [$id]);
$connection->query('SELECT * FROM user')->then(function (QueryCommand $command) {
if …
```
=> Use promises for query() method

README.md, examples/01-query.php, examples/11-interactive.php, src/Commands/AbstractCommand.php, src/Commands/AuthenticateCommand.php, src/Commands/CommandInterface.php, src/Commands/PingCommand.php, src/Commands/QueryCommand.php, src/Commands/QuitCommand.php, src/Connection.php, src/ConnectionInterface.php, src/Io/Parser.php, src/QueryResult.php, tests/NoResultQueryTest.php, tests/ResultQueryTest.php
Similar to #53, the whole `Command` class hierarchy is now marked as internal and will receive a number of patches to clean up its interfaces. The `query()` method now resolves with a `QueryResult` instead of a `QueryCommand`. Its public properties have been left unchanged, so migrating existing code should not be too hard.
Builds on top of #61 and #53
=> Use QueryResult instead of exposing QueryCommand and mark all commands as internal and move its base to Commands namespace

README.md, src/Connection.php, src/ConnectionInterface.php, tests/ConnectionTest.php
This PR updates the `ping()` method to use promises instead of accepting a required callback function.
```php
// old
$connection->ping(function ($error, $connection) {
if ($error) {
echo 'Error: ' . $error->getMessage() . PHP_EOL;
} else {
echo 'OK' . PHP_EOL;
}
});
// new 
$connection->ping(function () {
echo 'OK' . PHP_EOL;
}, function (Exception $error) {
echo 'Error: ' . $error->getMessage() . PHP_EOL;
});
```
This PR also includes relevant documentation and tests. The old method definition was somewhat inconsistent and under-documented.
Builds on top of #61 
Refs #4
=> Use promises for ping() method

README.md, examples/01-query.php, examples/02-query-stream.php, examples/11-interactive.php, src/ConnectionInterface.php, src/Io/Connection.php, tests/FactoryTest.php, tests/Io/ConnectionTest.php, tests/NoResultQueryTest.php, tests/ResultQueryTest.php
This PR renames the existing `close()` method to `quit()` and uses promises for this method instead.
```php
// old
$connection->close(function () {
echo 'closed';
});
// new
$connection->quit()->then(function () {
echo 'closed';
});
```
This PR also includes relevant documentation and tests. The old `close()` method definition was somewhat inconsistent and under-documented.
Builds on top of #64
Refs #4
=> Rename close() to quit() and use promises for quit() method

README.md, src/ConnectionInterface.php, src/Io/Connection.php
This simple PR updates the `ping()` method to resolve with a void value on success instead of a (rather pointless) boolean true value (recently introduced via #63). This means that this is now in line with the new `quit()` method (just introduced via #65).
Builds on top of #63 and #65
=> Update ping() to resolve with void value on success

src/Commands/AbstractCommand.php, src/Commands/CommandInterface.php, src/Io/Connection.php, src/Io/Parser.php
This simple PR removes a number of unneeded references from the internal Commands. This did not affect outside behavior and is not a BC break.
Builds on top of #62
=> Internal refactoring to remove unneeded references from Commands

src/ConnectionInterface.php, src/Io/Connection.php, tests/Io/ConnectionTest.php
This simple PR removes the (mostly under-documented) `getState()`, `getOptions()`, `setOptions()` and `getConnectionOptions()` methods from the `ConnectionInterface`. As of #64 and #65 the connection state is handled internally and is nothing consumers should have to worry about. Similarly, this now uses a URI for connecting instead of connection options.
This is a BC break obviously, but empirical evidence including our examples suggests this should not affect most consumers.
Builds on top of #64 and #65
=> Remove unneeded ConnectionInterface methods getState(), getOptions(), setOptions() and getServerOptions()

src/Commands/AbstractCommand.php, src/Commands/AuthenticateCommand.php, src/Commands/CommandInterface.php, src/Commands/PingCommand.php, src/Commands/QueryCommand.php, src/Commands/QuitCommand.php, src/Factory.php, src/Io/Connection.php, src/Io/Executor.php, src/Io/Parser.php, tests/FactoryTest.php, tests/Io/ConnectionTest.php, tests/Io/ParserTest.php
This PR simplifies connection logic by moving to Factory and authentication logic by moving to AuthenticateCommand. This is a prerequisite for a follow-up PR that introduces improved connection stream handling and a `close()` method (refs #65). It does not affect any of the outside behavior, so this is not a BC break.
Builds on top of #64 and #65
=> Internal refactoring to simplify connection and authentication logic

src/Factory.php, src/Io/Parser.php, tests/NoResultQueryTest.php
This PR fixes #70. This was caused by the `Parser` trying to execute multiple commands at the same time when commands are already queued and a new command is queued from a success handler. When the second command was completed, it would no longer have a reference to the command and would bail out. This is a side effect that was introduced with #52, but the underlying flaw has been present for much longer. The fix ensures we only ever take one command from the queue and then wait for it to finish.
Builds on top of #52
Supersedes / closes #74, thank you @elprawn
Resolves / closes #70
=> Fix executing queued commands in the order they are enqueued

README.md, src/ConnectionInterface.php, src/Io/Connection.php, tests/FactoryTest.php
The original `close()` method was renamed to `quit()` (via #65) to emphasize this method actually sends a "quit" command over the wire once all queued commands are done (it waits for all queued commands, which is also why it now returns a promise). It does not force-close the connection like the stream `close()` method commonly used in @reactphp does. This PR adds a new `close(): void` method which immediately force-closes the underlying connection and rejects all outstanding commands.
Being a new addition to the `ConnectionInterface`, this PR is technically a BC break. Empirical evidence suggests this should not affect most consumers (BC is limited due to #65 anyway).
Builds on top of #69 and #65
=> Add close() method to force-close the connection

README.md, examples/02-query-stream.php, examples/12-slow-stream.php, src/ConnectionInterface.php, src/Io/Connection.php, src/Io/QueryStream.php, tests/Io/QueryStreamTest.php, tests/ResultQueryTest.php
=> Support throttling streaming result sets from queryStream()

README.md, src/ConnectionInterface.php
The `Connection` class emits a `close` and `error` event under certain circumstances. These events are now defined on the `ConnectionInterface` to add some documentation for this and also for consumers to rely on this abstraction instead of a concretion.
Being a new addition to the `ConnectionInterface`, this PR is technically a BC break. Empirical evidence suggests this should not affect most consumers and some consumers already rely on this behavior anyway (see example 11).
Builds on top of #76
=> Define events on ConnectionInterface

src/Commands/QueryCommand.php, src/Io/Connection.php, src/Io/Parser.php, src/QueryResult.php, tests/NoResultQueryTest.php
A count of warnings is currently added via `Io\Parser::onSuccess()`. This value is dynamically added as attribute to the instance of `QueryCommand`.
This PR will add this value like `affected_rows` to the `QueryCommand` and `QueryResult` class and adds its actual value (if given) to the instance of these classes.
=> Add warningCount to QueryResult

src/Io/Parser.php, tests/Io/ParserTest.php
The server may reject an incoming connection during authentication or even before that during the initial connection handshake. The initial handshake error message uses a slightly different message format and also semantically happens *before* executing a command, so we now make sure to properly reject the *following* authentication command.
> Note:
In case the server sent a ERR packet as first packet it will happen before the client and server negotiated any capabilities. Therefore the ERR packet will not contain the SQL-state.
https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html
Resolves / closes #81
=> Fix parsing error message during handshake (Too many connections)

README.md, composer.json, src/Factory.php, tests/FactoryTest.php
Prerequisite for #72 
Builds on top of reactphp/socket#170 and reactphp/socket#177
Refs https://github.com/clue/reactphp-buzz/pull/110
=> Support cancellation of pending connection attempts

README.md, composer.json, examples/01-query.php, examples/02-query-stream.php, src/Factory.php, src/Io/LazyConnection.php, tests/FactoryTest.php, tests/Io/LazyConnectionTest.php, tests/ResultQueryTest.php
This PR implements a new `Factory::createLazyConnection()` method.
It helps with establishing a TCP/IP connection to your MySQL database
and issuing the initial authentication handshake.
```php
$connection = $factory->createLazyConnection($url);
$connection->query(…);
```
This method immediately returns a "virtual" connection implementing the
[`ConnectionInterface`](#connectioninterface) that can be used to
interface with your MySQL database. Internally, it lazily creates the
underlying database connection (which may take some time) only once the
first request is invoked on this instance and will queue all outstanding
requests until the underlying connection is ready.
From a consumer side this means that you can start sending queries to the
database right away while the actual connection …
=> Add new createLazyConnection() method to only connect only on demand (on first command) 

src/Commands/AuthenticateCommand.php, tests/FactoryTest.php, tests/ResultQueryTest.php
This simple PR fixes a bug that occurred when trying to connect to the database without giving a database name. While rarely used in practice, this might make sense for admin access to create a database or issue a `use "dbname"` query later on. This previously resulted in an exception with the message "bad handshake" during the connection due to invalid protocol usage.
=> Fix "bad handshake" error when connecting without database name

.travis.yml, composer.json, phpunit.xml.dist, tests/FactoryTest.php, tests/Io/BufferTest.php, tests/Io/QueryTest.php
Builds on top of clue/php-socket-raw#42
=> Test against PHP 7.3, add forward compatibility with PHPUnit 7 and use legacy PHPUnit 5 on HHVM

src/Factory.php
The Factory class uses a socket connection in order to create the
underlying database connection, but returns a higher-level MySQL
connection interface from its local namespace. By using an aliased
import, we no longer "overwrite" the local reference and fix IDE
autocompletion and static analysis tools.
=> Fix ConnectionInterface return type hint in Factory

src/Io/LazyConnection.php, tests/Io/LazyConnectionTest.php
When an operation fails because the underlying connection is closed, we
should never start an idle timer. There used to be a race condition that
the connection close event was detected before cancelling the pending
commands. We avoid this by checking the connection state before starting
an idle timer when an operation fails.
Closes #107 and #106, thanks @choval for reporting!
=> Do not start idle timer when lazy connection is already closed

README.md, composer.json, examples/01-query.php, examples/02-query-stream.php, examples/11-interactive.php, examples/12-slow-stream.php, src/Factory.php, tests/FactoryTest.php
This changeset simplifies usage by supporting the new [default loop](https://github.com/reactphp/event-loop#loop).
```php
// old (still supported)
$factory = new React\MySQL\Factory($loop);
// new (using default loop)
$factory = new React\MySQL\Factory();
```
Builds on top of https://github.com/reactphp/event-loop/pull/226, https://github.com/reactphp/event-loop/pull/229, https://github.com/reactphp/event-loop/pull/232, https://github.com/reactphp/stream/pull/159 and and https://github.com/reactphp/socket/pull/260
=> Simplify usage by supporting new default loop

README.md, src/Commands/AuthenticateCommand.php, src/Factory.php, src/Io/Query.php, tests/Commands/AuthenticateCommandTest.php, tests/FactoryTest.php, tests/ResultQueryTest.php
This changeset adds support for an optional `charset` parameter for full UTF-8 support (`utf8mb4`).
By default, the connection uses the `utf8` charset encoding. Note that
MySQL's `utf8` encoding (also known as `utf8mb3`) predates what is now
known as UTF-8 and for historical reasons doesn't support emojis and
other characters. If you want full UTF-8 support, you can pass the
charset encoding like this:
```php
$factory->createLazyConnection('localhost?charset=utf8mb4');
```
Resolves / closes #133
Refs #131
=> Support optional `charset` parameter for full UTF-8 support (`utf8mb4`)

README.md, composer.json, src/Factory.php, tests/FactoryTest.php, tests/NoResultQueryTest.php, tests/ResultQueryTest.php
This changeset simplifies usage by supporting the new Socket API without nullable loop arguments.
Note that this doesn't affect the API of this package at all, but does use the improved API of the referenced Socket component. Existing code continues to work as is.
Together with #134, this means we can now fully rely on the [default loop](https://github.com/reactphp/event-loop#loop) and no longer need to skip any arguments with null values.
Builds on top of reactphp/socket#264 and reactphp/socket#263
=> Simplify usage by supporting new Socket API and use new deafult loop in test suite

README.md, examples/12-slow-stream.php, src/Commands/AuthenticateCommand.php, src/ConnectionInterface.php, src/Factory.php, src/Io/Connection.php, src/Io/LazyConnection.php, src/Io/Parser.php, src/Io/Query.php, src/Io/QueryStream.php, tests/BaseTestCase.php, tests/FactoryTest.php, tests/Io/ConnectionTest.php, tests/Io/LazyConnectionTest.php, tests/Io/QueryStreamTest.php, tests/Io/QueryTest.php, tests/ResultQueryTest.php
I noticed that this project still uses the `array()` notation instead of `[]`. The `array()` notation was needed for PHP version < 5.4 which is not the case in this project.
I know it's not a necessary change so if there is any good reason to keep the old stuff let me know.
=> Replace array() with [] and minor clean up

src/Factory.php, tests/FactoryTest.php
With these changes it's possible to pass an URI scheme to your `createconnection()`. 
If no scheme is given it defaults to `mysql://`
If you pass an invalid URI scheme (anything other than `mysql://`) it will be rejected with an `InvalidArgumentException`
=> Support URI scheme to create connection

src/Io/Query.php, tests/Io/QueryTest.php, tests/ResultQueryTest.php
This changeset provides limited support for the `NO_BACKSLASH_ESCAPES` SQL mode. From my experience I would say this is rarely used in practice and using the `NO_BACKSLASH_ESCAPES` SQL mode is usually not recommended. Accordingly, this changeset has no effect on most installations.
When the `NO_BACKSLASH_ESCAPES` SQL mode is used, backslash escapes such as `\'` will no longer be interpreted as a single character but instead as the two literals. This means we have to take special care when trying to escape string values that contain a `'` character to avoid possible SQL injections. Instead, we can replace each `'` with `''` which ends up being interpreted as a single `'` irrespective of whether the `NO_BACKSLASH_ESCAPES` SQL mode is used. Accordingly, I've removed most unneeded escape …
=> Provide limited support for `NO_BACKSLASH_ESCAPES` SQL mode

README.md, examples/01-query.php, examples/02-query-stream.php, examples/11-interactive.php, examples/12-slow-stream.php, src/Factory.php, src/Io/Connection.php, src/Io/Parser.php, tests/FactoryTest.php, tests/Io/ConnectionTest.php, tests/Io/ParserTest.php
This changeset improves error reporting to include the MySQL URI and socket error codes in all connection errors:
```diff
- Error: Unable to connect to database server
- Error: Access denied for user 'test'@'::1' (using password: YES)
+ Error: Connection to mysql://test:***@localhost/test failed: Connection to localhost:3306 failed: Last error for IPv4: Connection to tcp://127.0.0.1:3306?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:3306?hostname=localhost failed: Connection refused
+ Error: Connection to mysql://test:***@localhost/test failed during authentication: Access denied for user 'test'@'::1' (using password: YES) (EACCES)
```
Builds on top of #138, https://github.com/clue/reactphp-redis/pull/116, …
=> Improve error reporting, include MySQL URI and socket error codes in all connection errors

.github/workflows/ci.yml, README.md, composer.json, phpunit.xml.legacy, tests/BaseTestCase.php, tests/Io/BufferTest.php, tests/Io/LazyConnectionTest.php, tests/NoResultQueryTest.php
PHPUnit 9.3 released a new schema for the `phpunit.xml` configuration file. I had to migrate the file to the new format in order to avoid the warning. PHPUnit Versions older than 9.3 have to use the `phpunit.xml.legacy` configuration file, because the new format is unknown for them.
For further details concerning this pull request look into https://github.com/graphp/graphviz/pull/46.
This pull request builds on top of #132.
It's also possible to run this code with PHP 8 🎉
```bash
$ docker run -it --rm -v `pwd`:/data --net=host --workdir=/data php:8.0.0 php vendor/bin/phpunit
PHPUnit 9.5.8 by Sebastian Bergmann and contributors.
...............................................................  63 / 201 ( 31%)
............................................................... 126 / 201 ( 62%) …
```
=> Run tests on PHPUnit 9 and PHP 8

.gitattributes
=> Add `.gitattributes` to exclude dev files from export

.github/workflows/ci.yml, composer.json, phpunit.xml.dist, phpunit.xml.legacy, src/Io/LazyConnection.php, tests/ResultQueryTest.php
This changeset adds support for PHP 8.1.
~~I'm marking this as WIP because it currently reports a deprecation notice that needs to be addressed upstream first (https://github.com/reactphp/promise-timer/pull/50). I'll update this PR once this version is released.~~
Builds on top of #142
Resolves / closes #149
=> Support PHP 8.1
